version: "3.9"

services:
  kong:
    container_name: kong-dbless
    image: kong/kong-gateway:3.4
    volumes:
      - ./kong/:/kong/declarative/
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_LICENSE_DATA
    ports:
      - "8000:8000"
    networks:
      - kong-keycloak

networks:
  kong-keycloak:
